import Head from 'next/head';
// import styled from 'styled-components';
import tw, { styled } from 'twin.macro';

export default function Home() {
  return (
    <div className="bg-primary-light flex flex-col items-center justify-center min-h-screen py-2">
      <Head>
        <title>&nbsp;a-sh-dev.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex gap-4 flex-col items-center justify-center w-full flex-1 px-20">
        <h1 className="font-extrabold text-8xl pt-6 text-primary-dark">
          Hello World!
        </h1>
        <p className="text-left text-lg">
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quis eius
          magni sapiente, corrupti dolor expedita, distinctio, consequatur
          excepturi fuga architecto totam aspernatur qui temporibus veniam
          eligendi ducimus facilis dolore sed?
        </p>
        <span className="font-mono italic">And I'm loving it! So far</span>
      </main>
    </div>
  );
}
