import Head from 'next/head';
// import styled from 'styled-components';
import tw, { styled } from 'twin.macro';

export default function Home() {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen py-2">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex gap-4 flex-col items-center justify-center w-full flex-1 px-20 text-center">
        <StyledButton>Styled-Component</StyledButton>
        <TWStyledButton>TW-SC</TWStyledButton>
        <ComboBtn isRed>COMBO</ComboBtn>
      </main>
    </div>
  );
}

// testing TW sc
const TWStyledButton = tw.button`
  bg-red-500
  hover:bg-red-700
  text-white
  font-bold
  py-2
  px-4
  border
  border-black
  rounded
`;

// testing styled-components
const StyledButton = styled.button`
  background: red;
  color: white;
  font-size: 1em;
  text-align: center;
  padding: 0.25em 1em;
  border: 2px solid black;
`;

// testing conditional button
const ComboBtn = styled.button(({ isRed }) => [
  isRed
    ? tw`bg-red-400 hover:bg-red-900`
    : tw`bg-indigo-600 hover:bg-indigo-500`,
  tw`
    text-white
    font-bold
    font-mono
    py-2
    px-4
    border
    border-black
    rounded-full
  `,
]);
