import Head from 'next/head';
import Image from 'next/image';
// import styled from 'styled-components';
import 'twin.macro';
import { RiEmotionHappyLine } from 'react-icons/ri';
import { AshLogo } from '../components/svgs';

export default function Home() {
  return (
    <div className="bg-primary-light flex flex-col items-center justify-center min-h-screen py-2">
      <Head>
        <title>&nbsp;a-sh-dev.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex gap-4 flex-col items-center justify-center w-full flex-1 px-20">
        <AshLogo className="text-primary-dark text-8xl" />
        <h1 className="font-extrabold text-8xl pt-6 text-primary-dark">
          Hello World!
        </h1>
        <Image
          src="/images/plus_white.svg"
          alt="test svg"
          width={72}
          height={72}
        />

        <p className="text-left text-lg">
          <span className="inline-block mr-2 text-primary-dark">
            <RiEmotionHappyLine />
          </span>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quis eius
          magni sapiente, corrupti dolor expedita, distinctio, consequatur
          excepturi fuga architecto totam aspernatur qui temporibus veniam
          eligendi ducimus facilis dolore sed?
        </p>
        <span className="font-mono italic">And I am loving it! So far</span>
      </main>
    </div>
  );
}
